updateDocsComment: >
  Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update some of our documentation based on your changes. You can run `yarn generate-docs` to generate some!
# Terms that if found in the title of a PR will prevent the bot from commenting on it
updateDocsWhiteList:
  - bug
  - chore